name: Tests

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "tests/**"
jobs:
  tests:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: vendor/bin/phpunit